name: Build Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-static:
    name: Build static app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: static
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          package_json_file: static/package.json
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build static app
        run: pnpm build

  build-server:
    name: Build server image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build server image
        uses: docker/build-push-action@v6
        with:
          context: server/
          push: false
